Use auto tag
pxblue/angular-component-library pull request #314
Opened 2021-07-20 16:57 UTC by emclaug2

#### Changes proposed in this Pull Request:
- Use auto tag

2021-07-20 19:30 UTC, joebochill requested changes

2021-07-20 19:30 UTC, joebochill commented on .circleci/config.yml
> +            name: Tag @pxblue/tag
```suggestion
            name: Tag @pxblue/angular-components
```

2021-07-21 14:43 UTC, emclaug2 commented on .circleci/config.yml
> +            name: Tag @pxblue/tag
Fixed now

2021-07-21 18:38 UTC, joebochill approved these changes

2021-07-21 18:38 UTC, merged